// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PJATK_APBD_Cw4_s20788.Data;

#nullable disable

namespace PJATK_APBD_Cw4_s20788.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525200401_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PJATK_APBD_Cw4_s20788.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturerId")
                        .HasColumnType("int")
                        .HasColumnName("ComponentManufacturersId");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ComponentTypesId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturerId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "CPU001",
                            ComponentManufacturerId = 1,
                            ComponentTypeId = 1,
                            Description = "High performance desktop processor",
                            Name = "Intel Core i7-14700K"
                        },
                        new
                        {
                            Code = "GPU001",
                            ComponentManufacturerId = 2,
                            ComponentTypeId = 2,
                            Description = "Graphics card for gaming and productivity",
                            Name = "NVIDIA GeForce RTX 4070"
                        },
                        new
                        {
                            Code = "RAM001",
                            ComponentManufacturerId = 3,
                            ComponentTypeId = 3,
                            Description = "DDR5 memory kit",
                            Name = "Kingston Fury 32GB DDR5"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s20788.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "INTEL",
                            FoundationDate = new DateTime(1968, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Intel Corporation"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "NVIDIA",
                            FoundationDate = new DateTime(1993, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "NVIDIA Corporation"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "KINGSTON",
                            FoundationDate = new DateTime(1987, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Kingston Technology"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s20788.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Processor"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Card"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Memory"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s20788.Models.Pc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PCs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast X",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 12.5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Mini Pro",
                            Stock = 12,
                            Warranty = 24,
                            Weight = 4.2000000000000002
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 20, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Name = "Workstation Ultra",
                            Stock = 3,
                            Warranty = 48,
                            Weight = 15.800000000000001
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s20788.Models.PcComponent", b =>
                {
                    b.Property<int>("PcId")
                        .HasColumnType("int")
                        .HasColumnName("PCId");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PcId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents", (string)null);

                    b.HasData(
                        new
                        {
                            PcId = 1,
                            ComponentCode = "CPU001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "GPU001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "RAM001",
                            Amount = 2
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "CPU001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "RAM001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "CPU001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "GPU001",
                            Amount = 2
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s20788.Models.Component", b =>
                {
                    b.HasOne("PJATK_APBD_Cw4_s20788.Models.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_Cw4_s20788.Models.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s20788.Models.PcComponent", b =>
                {
                    b.HasOne("PJATK_APBD_Cw4_s20788.Models.Component", "Component")
                        .WithMany("PcComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_Cw4_s20788.Models.Pc", "Pc")
                        .WithMany("PcComponents")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s20788.Models.Component", b =>
                {
                    b.Navigation("PcComponents");
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s20788.Models.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s20788.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s20788.Models.Pc", b =>
                {
                    b.Navigation("PcComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
